export const LAST_UPDATED = 'Apr 12, 2026 · 9:05 PM';

export const FIELD_DEFS = {
  project_n1: {
    label: 'Project N1',
    width: 50,
    length: 100,
    bunkers: [
      { id: 'can', label: 'Can', desc: 'Medium cylinder', color: '#10b981', cat: 'Cylinders' },
      { id: 'fatboy', label: 'Fatboy', desc: 'Large cylinder', color: '#ef4444', cat: 'Cylinders' },
      { id: 'cake', label: 'Cake', desc: 'Wide flat disk', color: '#ec4899', cat: 'Cylinders' },
      { id: 'dorito', label: 'Dorito', desc: 'Triangle prism', color: '#f59e0b', cat: 'Triangles' },
      { id: 'mini_dorito', label: 'Mini Dorito', desc: 'Small triangle', color: '#fbbf24', cat: 'Triangles' },
      { id: 'brick', label: 'Brick', desc: 'Wide low wall', color: '#8b5cf6', cat: 'Rectangles' },
      { id: 'tombstone', label: 'Tombstone', desc: 'Tall thin wall', color: '#06b6d4', cat: 'Rectangles' },
      { id: 'sup_air', label: "Sup'Air", desc: 'Tall wide wall', color: '#3b82f6', cat: 'Rectangles' },
      { id: 'snake', label: 'Snake', desc: 'Full S-shape', color: '#6366f1', cat: 'Snakes' },
      { id: 'mini_snake', label: 'Mini Snake', desc: 'Half S-shape', color: '#818cf8', cat: 'Snakes' },
      { id: 'tck', label: 'TCK', desc: 'T-shape bunker', color: '#f97316', cat: 'Complex' },
      { id: 'corner', label: 'Corner', desc: 'L-shape corner', color: '#84cc16', cat: 'Complex' },
      { id: 'x_bunker', label: 'X-Bunker', desc: 'Cross shape', color: '#a78bfa', cat: 'Complex' },
    ],
  },
  tac_city: {
    label: 'Tac City Airsoft',
    width: 50,
    length: 100,
    bunkers: [
      { id: 'can', label: 'Can', desc: 'Medium cylinder', color: '#10b981', cat: 'Cylinders' },
      { id: 'fatboy', label: 'Fatboy', desc: 'Large cylinder', color: '#ef4444', cat: 'Cylinders' },
      { id: 'dorito', label: 'Dorito', desc: 'Triangle prism', color: '#f59e0b', cat: 'Triangles' },
      { id: 'brick', label: 'Brick', desc: 'Wide low wall', color: '#8b5cf6', cat: 'Rectangles' },
      { id: 'tombstone', label: 'Tombstone', desc: 'Tall thin wall', color: '#06b6d4', cat: 'Rectangles' },
      { id: 'sup_air', label: "Sup'Air", desc: 'Tall wide wall', color: '#3b82f6', cat: 'Rectangles' },
      { id: 'snake', label: 'Snake', desc: 'Full S-shape', color: '#6366f1', cat: 'Snakes' },
      { id: 'tck', label: 'TCK', desc: 'T-shape bunker', color: '#f97316', cat: 'Complex' },
      { id: 'corner', label: 'Corner', desc: 'L-shape corner', color: '#84cc16', cat: 'Complex' },
    ],
  },
  adrenaline: {
    label: 'Adrenaline Paintball',
    width: 50,
    length: 100,
    bunkers: [
      { id: 'can', label: 'Can', desc: 'Medium cylinder', color: '#ff2d55', cat: 'Cylinders' },
      { id: 'fatboy', label: 'Fatboy', desc: 'Large cylinder', color: '#ff9500', cat: 'Cylinders' },
      { id: 'cake', label: 'Cake', desc: 'Wide flat disk', color: '#ffcc00', cat: 'Cylinders' },
      { id: 'dorito', label: 'Dorito', desc: 'Triangle prism', color: '#34c759', cat: 'Triangles' },
      { id: 'mini_dorito', label: 'Mini Dorito', desc: 'Small triangle', color: '#5ac8fa', cat: 'Triangles' },
      { id: 'brick', label: 'Brick', desc: 'Wide low wall', color: '#007aff', cat: 'Rectangles' },
      { id: 'tombstone', label: 'Tombstone', desc: 'Tall thin wall', color: '#af52de', cat: 'Rectangles' },
      { id: 'sup_air', label: "Sup'Air", desc: 'Tall wide wall', color: '#ff3b30', cat: 'Rectangles' },
      { id: 'snake', label: 'Snake', desc: 'Full S-shape', color: '#30d158', cat: 'Snakes' },
      { id: 'mini_snake', label: 'Mini Snake', desc: 'Half S-shape', color: '#64d2ff', cat: 'Snakes' },
      { id: 'tck', label: 'TCK', desc: 'T-shape bunker', color: '#ff6b00', cat: 'Complex' },
      { id: 'corner', label: 'Corner', desc: 'L-shape corner', color: '#ffd60a', cat: 'Complex' },
      { id: 'x_bunker', label: 'X-Bunker', desc: 'Cross shape', color: '#ff375f', cat: 'Complex' },
    ],
  },
};

export const DEFAULT_LAYOUTS = {
  project_n1: [
    { type: 'x_bunker', x: 0, z: 0, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'snake', x: 12.5, z: 10, rotY: 0.7853981633974481, scaleX: 1, scaleZ: 1 },
    { type: 'snake', x: 12.5, z: -10, rotY: -1.0471975511965976, scaleX: 1, scaleZ: -1 },
    { type: 'tombstone', x: 15, z: 0, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'tombstone', x: 15, z: 0, rotY: 0, scaleX: 1, scaleZ: -1 },
    { type: 'tombstone', x: -20, z: 15, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'tombstone', x: -20, z: -15, rotY: 0, scaleX: 1, scaleZ: -1 },
    { type: 'tombstone', x: -12.5, z: 5, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'tombstone', x: -12.5, z: -5, rotY: 0, scaleX: 1, scaleZ: -1 },
    { type: 'can', x: -20, z: 32.5, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'can', x: -20, z: -32.5, rotY: 0, scaleX: 1, scaleZ: -1 },
    { type: 'can', x: 0, z: 32.5, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'can', x: 0, z: -32.5, rotY: 0, scaleX: 1, scaleZ: -1 },
    { type: 'can', x: 17.5, z: 32.5, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'can', x: 17.5, z: -32.5, rotY: 0, scaleX: 1, scaleZ: -1 },
    { type: 'fatboy', x: 0, z: 15, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'fatboy', x: 0, z: -15, rotY: 0, scaleX: 1, scaleZ: -1 },
  ],
  tac_city: [
    { type: 'brick', x: 0, z: -47, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'brick', x: 0, z: 47, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'x_bunker', x: 0, z: 0, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'snake', x: 12.5, z: 10, rotY: 0.7853981633974481, scaleX: 1, scaleZ: 1 },
    { type: 'snake', x: 12.5, z: -10, rotY: -1.0471975511965976, scaleX: 1, scaleZ: -1 },
    { type: 'tombstone', x: 15, z: 0, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'tombstone', x: 15, z: 0, rotY: 0, scaleX: 1, scaleZ: -1 },
    { type: 'tombstone', x: -20, z: 15, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'tombstone', x: -20, z: -15, rotY: 0, scaleX: 1, scaleZ: -1 },
    { type: 'tombstone', x: -12.5, z: 5, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'tombstone', x: -12.5, z: -5, rotY: 0, scaleX: 1, scaleZ: -1 },
    { type: 'can', x: -20, z: 32.5, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'can', x: -20, z: -32.5, rotY: 0, scaleX: 1, scaleZ: -1 },
    { type: 'can', x: 0, z: 32.5, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'can', x: 0, z: -32.5, rotY: 0, scaleX: 1, scaleZ: -1 },
    { type: 'can', x: 17.5, z: 32.5, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'can', x: 17.5, z: -32.5, rotY: 0, scaleX: 1, scaleZ: -1 },
    { type: 'fatboy', x: 0, z: 15, rotY: 0, scaleX: 1, scaleZ: 1 },
    { type: 'fatboy', x: 0, z: -15, rotY: 0, scaleX: 1, scaleZ: -1 },
  ],
  adrenaline: [
    { type: 'mini_dorito', x: 0, z: 4, rotY: 0 },
    { type: 'mini_dorito', x: 0, z: -4, rotY: Math.PI },
    { type: 'snake', x: -20, z: 18, rotY: 0 },
    { type: 'snake', x: -20, z: -18, rotY: 0 },
    { type: 'dorito', x: -8, z: 24, rotY: 0 },
    { type: 'dorito', x: -8, z: -24, rotY: 0 },
    { type: 'dorito', x: 8, z: 24, rotY: Math.PI },
    { type: 'dorito', x: 8, z: -24, rotY: Math.PI },
    { type: 'tck', x: 5, z: 10, rotY: 0 },
    { type: 'tck', x: 5, z: -10, rotY: Math.PI },
    { type: 'can', x: 18, z: 10, rotY: 0 },
    { type: 'can', x: 18, z: -10, rotY: 0 },
    { type: 'fatboy', x: 0, z: 18, rotY: 0 },
    { type: 'fatboy', x: 0, z: -18, rotY: 0 },
    { type: 'can', x: -20, z: 38, rotY: 0 },
    { type: 'can', x: -20, z: -38, rotY: 0 },
    { type: 'can', x: 20, z: 38, rotY: 0 },
    { type: 'can', x: 20, z: -38, rotY: 0 },
    { type: 'sup_air', x: -12, z: 42, rotY: 0 },
    { type: 'sup_air', x: -12, z: -42, rotY: 0 },
    { type: 'sup_air', x: 12, z: 42, rotY: 0 },
    { type: 'sup_air', x: 12, z: -42, rotY: 0 },
    { type: 'mini_snake', x: 20, z: 28, rotY: -0.785 },
    { type: 'mini_snake', x: 20, z: -28, rotY: 0.785 },
  ],
};

export const RELEASES = [
  {
    version: 'Roadmap',
    date: 'Upcoming',
    badge: 'roadmap',
    items: [
      '<strong>Real bunker dimensions</strong> — replace placeholder geometry with exact measured specs from Project N1 and Tac City Airsoft',
      '<strong>FPS mode (PC only)</strong> — first-person walkthrough is a desktop feature; requires mouse + pointer lock; not available on mobile/tablet',
      '<strong>Share layout</strong> — generate a shareable URL or QR code so you can send a layout to your team instantly',
      '<strong>Additional fields</strong> — want your field represented in the app? Reach out to <a href="https://www.instagram.com/bryan.paintball/" target="_blank" rel="noopener" style="color:var(--blue)">@bryan.paintball</a> on Instagram',
    ],
  },
  {
    version: 'v1.0',
    date: 'Apr 2026',
    badge: 'latest',
    items: [
      '<strong>Unlimited play slots</strong> — no more 8-play cap; add as many plays as you need with the + button',
      '<strong>Export Save includes everything</strong> — Export Save now saves all play slots, arrows, playbook state, and field data in one file',
      '<strong>Adrenaline Paintball field</strong> — new field added with full NXL-style bunker palette in bright paintball colors',
      '<strong>Player height & width</strong> — right-click any player to adjust their height (70–130%) and width (70–150%) with sliders',
      '<strong>Carpinteros skin tones</strong> — 64% of Carpinteros players spawn with varied brown skin tones; the remaining 36% get light skin. Light-skin players do not wear a sombrero',
      '<strong>Mobile multi-select</strong> — new Multi button in the toolbar; tap to enable, then tap objects to add/remove from the selection group for CW/CCW/Delete on touch devices',
    ],
  },
  {
    version: 'v0.9',
    date: 'Apr 2026',
    badge: '',
    items: [
      '<strong>Playbook system</strong> — save up to 8 plays per field; each play stores players + arrows while bunkers stay fixed; click a slot to auto-save current and switch',
      '<strong>Dynamic play slots</strong> — starts with Play 1; tap + to add more slots as needed',
      '<strong>Arrows follow camera</strong> — arrows are stored in 3D world space and re-projected every frame, so they rotate and zoom with the camera',
      '<strong>Player paintball masks</strong> — every player wears a JT Proflex-style mask with randomised mask color, lens, skin tone, and hair',
      '<strong>Weapon models</strong> — distinct AR-15 rifle, M870 shotgun, and Glock pistol silhouettes based on weapon selection',
      '<strong>Player scale</strong> — figures scaled to 5\'10" for realistic field proportion',
      '<strong>Players face midfield</strong> — newly placed players automatically face the centre line',
      '<strong>Hold to rotate</strong> — holding CW / CCW buttons continuously rotates the selected object on both PC and mobile',
      '<strong>Double-tap to rename</strong> — double-tap any placed bunker or player on mobile to rename it',
      '<strong>Per-field layout memory</strong> — each field saves its own layout independently; switching fields no longer wipes your work',
      '<strong>Reset to field default</strong> — ↺ button next to the field dropdown restores the original layout for that field',
      '<strong>Bunker recolor</strong> — right-click any bunker to set a custom color or reset to default; global Color / Black toggle also moved to right-click menu',
      '<strong>Selection ring only</strong> — removed emissive orange glow on selection; cyan ring is sufficient and doesn\'t interfere with recoloring',
      '<strong>Multi-select drag fixed</strong> — clicking a member of a multi-selection no longer collapses it; drag moves the whole group',
      '<strong>Multi-select context menu</strong> — right-clicking a selected object preserves the group selection; Rename hidden when multiple selected',
      '<strong>Layout slots removed</strong> — replaced by the Playbook; Export Save / Import Save for full backups',
      '<strong>Field Settings modal</strong> — field dimensions and environment colors moved to a dedicated modal',
      '<strong>Controls & Tips modal</strong> — moved out of sidebar into a button near the app title',
      '<strong>No backdrop blur on modals</strong> — scene remains fully visible behind modals',
    ],
  },
  {
    version: 'v0.8',
    date: 'Apr 2026',
    items: [
      '<strong>Flip feature removed</strong> — bunkers can only be rotated, not flipped; H/V buttons and keyboard shortcuts removed',
      '<strong>Default layouts</strong> — both Project N1 and Tac City Airsoft load a ready-made symmetrical speedsoft layout on first open or field switch',
      '<strong>Tac City starting walls</strong> — rectangular brick bunkers placed at both short-end centres to represent the spawn/starting walls',
    ],
  },
  {
    version: 'v0.7',
    date: 'Apr 2026',
    items: [
      '<strong>Shot arrows forced straight</strong> — Shot-type arrows are always a straight line (click + drag to aim); Move arrows remain freehand',
      '<strong>Shot arrows default neon green</strong> — switching to Shot auto-selects #39ff14; neon green swatch added to colour picker',
      '<strong>Release notes modal</strong> — this panel; button near app title in the sidebar',
      '<strong>App renamed</strong> — "Speedsoft Layout Planner" throughout; "SpeedQB" subtitle removed',
      '<strong>Shadows removed</strong> — cleaner render, better performance on all devices',
      '<strong>Bunker type rename in sidebar</strong> — ✎ button on each bunker card renames the type for future drops; placed instances unaffected',
      '<strong>Callout feature removed</strong> — replaced by a unified per-instance rename (right-click or double-click a placed bunker)',
      '<strong>Tracer toggle removed</strong> — T-key tracer feature removed for simplicity',
      '<strong>Single-Escape exits FPS</strong> — pressing Escape once now reliably exits FPS mode and restores 3D view',
      '<strong>FPS bunker collision</strong> — player can no longer walk through placed bunkers; slides along surfaces',
      '<strong>FPS field boundary</strong> — player cannot walk outside the field perimeter',
      '<strong>WASD freecam in 3D mode</strong> — arrow/WASD keys pan the orbit camera in layout mode',
      '<strong>FPS renamed from Walk</strong> — button and mode now labelled "FPS"',
      '<strong>Crosshair in FPS</strong> — white + crosshair shown at screen centre',
      '<strong>Pointer Lock</strong> — FPS mode captures the cursor for unlimited 360° look; click canvas to re-acquire',
      '<strong>Exit FPS → 3D view</strong> — leaving FPS snaps camera back to standard overhead 3D orbit',
      '<strong>Player models grounded</strong> — figures now stand with feet exactly on the field surface',
      '<strong>Realistic jump height</strong> — ~1.5 ft vertical with natural arc (~0.5 s to peak)',
      '<strong>FPS eye height fixed</strong> — POV is at head level (~5.3 ft) matching the 6 ft player model',
      '<strong>Rotation precision</strong> — bunker rotate buttons now step 15° per click (was 45°)',
      '<strong>Long-press context menu</strong> — 500 ms long-press on mobile opens right-click menu',
      '<strong>Visit counter removed</strong>',
    ],
  },
  {
    version: 'v0.6',
    date: 'Apr 2026',
    items: [
      '<strong>FPS / Walk mode</strong> — press F or the FPS button to enter first-person view; WASD to move, mouse to look',
      '<strong>FPS physics</strong> — Crouch (C), Crawl (Z), Jump (Space), Sprint (Shift), Dive (Shift+Z), Slide (Shift+C)',
      '<strong>BB shooting simulator</strong> — left-click in FPS fires a .25g BB at ~313 ft/s with hop-up straight flight then drop',
      '<strong>Impact flash</strong> — white flash sphere on BB hit',
      '<strong>Arrow types</strong> — Move (solid, freehand) and Shot (dashed) arrow styles',
      '<strong>Multi-select</strong> — Shift+click to add to selection; box-select by dragging on empty canvas; transforms affect all selected',
      '<strong>Right-click context menu</strong> — Rename, Duplicate, Delete on any bunker or player',
      '<strong>Auto-save</strong> — layout saved to localStorage on every change; restored on page reload',
      '<strong>Per-instance callouts</strong> — each placed bunker could store red/blue team callout names (later replaced by unified rename)',
      '<strong>Field distance rulers</strong> — Units ON/OFF toggle draws distance markers on the field',
    ],
  },
  {
    version: 'v0.5',
    date: 'Apr 2026',
    items: [
      '<strong>Layout slots</strong> — 4 save/load slots with custom names; Export / Import JSON',
      '<strong>Undo / Redo</strong> — separate stacks for scene changes and arrow strokes; Ctrl+Z / Ctrl+Y',
      '<strong>Duplicate</strong> — Ctrl+D duplicates selected bunker',
      '<strong>Bunker labels</strong> — Labels toggle shows name tag above each placed bunker',
      '<strong>Screenshot</strong> — downloads a PNG of the current layout',
      '<strong>Sidebar collapse</strong> — panel can be hidden to give more canvas space; reopens with arrow button',
    ],
  },
  {
    version: 'v0.4',
    date: 'Apr 2026',
    items: [
      '<strong>Player markers</strong> — human figure models with team colour (red/blue) and weapon badge; draggable',
      '<strong>Draw arrows</strong> — freehand arrows with colour and thickness picker; separate canvas overlay',
      '<strong>Mirror mode</strong> — symmetrical bunker placement across the field centre line',
      '<strong>Snap to grid</strong> — 2.5 ft grid snap toggle',
      '<strong>Flip H / Flip V</strong> — mirror a selected bunker horizontally or vertically',
    ],
  },
  {
    version: 'v0.3',
    date: 'Apr 2026',
    items: [
      '<strong>Field selector</strong> — Project N1 and Tac City Airsoft presets with editable width/length',
      '<strong>Mobile support</strong> — sidebar becomes a bottom sheet; bunkers scroll horizontally; touch drag-and-drop',
      '<strong>Apple-style UI</strong> — SF Pro font stack, dark glass sidebar, pill buttons, smooth transitions',
    ],
  },
  {
    version: 'v0.2',
    date: 'Apr 2026',
    items: [
      '<strong>Bunker library</strong> — Can, Fatboy, Cake, Dorito, Mini Dorito, Brick, Tombstone, Sup\'Air, Snake, Mini Snake, TCK, Corner, X-Bunker',
      '<strong>Drag-and-drop placement</strong> — drag from sidebar onto field; click to arm then click-to-place',
      '<strong>Rotate CW / CCW</strong> — R / E keys or toolbar buttons',
      '<strong>Delete</strong> — Del key or toolbar button',
      '<strong>Top view / 3D view</strong> — toolbar camera presets',
      '<strong>Clear All</strong> — removes all placed bunkers',
    ],
  },
  {
    version: 'v0.1',
    date: 'Apr 2026',
    items: [
      '<strong>Initial build</strong> — Three.js scene with field plane, grid, ambient + directional lighting',
      '<strong>OrbitControls</strong> — right-click orbit, middle-click pan, scroll zoom; floor clamp',
      '<strong>Basic bunker shapes</strong> — placeholder geometry for common speedsoft bunkers',
    ],
  },
];
